version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: olist_orders
      - name: olist_order_items
      - name: olist_products
      - name: olist_customers
      - name: olist_sellers
      - name: olist_order_reviews
      - name: olist_order_payments
